# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
#paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://theryanmiller.github.io/
basurl: /
title: Ryan Miller
author: Ryan Miller
description: Personal blog and resume
avatar: ryan.png
email: rmiller07@gmail.com
github: theryanmiller
twitter: theryanmiller
google_analytics: 
