url: https://theryanmiller.com
baseurl: ""
title: Ryan Miller
author: Ryan Miller
description: Notes on software, systems, security, and things Ryan Miller builds.
github: theryanmiller
google_analytics: G-VSMQLWD6CV

permalink: /:title.html
markdown: kramdown
highlighter: rouge
theme:
kramdown:
  input: GFM

port: 5000
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
