# top level stuff you probably don't need to touch
#highlighter: pygments
highlighter: rouge
kramdown:
  input: GFM
markdown: kramdown
extensions: [smart]
permalink: /:title.html
_yaml_mode: loose
_content_type: markdown
_markdown_parser: parsedown
#paginate: 5
port: 5000
safe: true



# edit here to achieve your personal greatness
url: http://theryanmiller.github.io/
basurl: /
title: Ryan Miller
author: Ryan Miller
description: Personal blog and resume
avatar: headshot2.jpg
email: rmiller07@gmail.com
github: theryanmiller
twitter: real_mills
google_analytics: UA-89475228-1

